### ISSUE TITLE
Updated documentation tools

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/release-tools#13]
Currently, the build scripts are using the stock Doxygen which is at 1.8.6. It would be nice to use the newest version, 1.8.14, since it understands more of the modern C++ constructs. I believe the script to install the build tools is here:
https://github.com/boostorg/release-tools/blob/develop/ci_boost_release.py

While we are there, it would also be nice to install Saxon-HE ("home edition", free license) so that we have the option to write our XSLT using version 3.0 of the specification:
https://sourceforge.net/projects/saxon/files/

The current **xsltproc** being used only supports 1.0, and will never be updated / has reached the end-of-life. Saxon requires Java since it is a set of jar files, but maybe the container already has java. If not, it will need to be installed.

**Comment by vinniefalco** [comment]
@mjcaisse ping?

**Comment by mjcaisse** [comment]
Vinnie worked this out and got packages updated in the docker image. Closing out.
